# Generated by Django 4.0.1 on 2022-01-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, verbose_name='original url')),
                ('shorter_url', models.CharField(max_length=200, verbose_name='shorter url')),
            ],
        ),
    ]
